// <auto-generated />
using System;
using Knjizara.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Knjizara.DAL.Context.Migrations
{
    [DbContext(typeof(KnjizaraContext))]
    [Migration("20190728212152_KorisnikIRola")]
    partial class KorisnikIRola
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knjizara.Common.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<string>("Ime");

                    b.Property<string>("KorisnickoIme");

                    b.Property<string>("Lozinka");

                    b.Property<string>("Mail");

                    b.Property<double>("Plata");

                    b.Property<string>("Pol");

                    b.Property<string>("Prezime");

                    b.Property<int>("RolaId");

                    b.Property<string>("Telefon");

                    b.HasKey("KorisnikId");

                    b.HasIndex("RolaId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Knjizara.Common.Models.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("ProizvodId");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Knjizara.Common.Models.Racun", b =>
                {
                    b.Property<int>("SifraRacuna")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("UkupanIznos");

                    b.Property<DateTime>("VremeIzdavanja");

                    b.HasKey("SifraRacuna");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("Knjizara.Common.Models.Rola", b =>
                {
                    b.Property<int>("RolaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("RolaId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Knjizara.Common.Models.StavkaRacuna", b =>
                {
                    b.Property<int>("StavkaRacunaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Barkod");

                    b.Property<double>("CenaPoJedinici");

                    b.Property<int>("Kolicina");

                    b.Property<int>("SifraRacuna");

                    b.HasKey("StavkaRacunaId");

                    b.HasIndex("Barkod");

                    b.HasIndex("SifraRacuna");

                    b.ToTable("StavkeRacuna");
                });

            modelBuilder.Entity("Knjizara.Common.Models.VrstaProizvoda", b =>
                {
                    b.Property<int>("Barkod")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena");

                    b.Property<int>("Kolicina");

                    b.Property<string>("Naziv");

                    b.Property<int>("ProizvodId");

                    b.Property<string>("Proizvodjac");

                    b.Property<string>("ZemljaPorekla");

                    b.HasKey("Barkod");

                    b.HasIndex("ProizvodId");

                    b.ToTable("VrsteProizvoda");
                });

            modelBuilder.Entity("Knjizara.Common.Models.Korisnik", b =>
                {
                    b.HasOne("Knjizara.Common.Models.Rola", "Rola")
                        .WithMany()
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Knjizara.Common.Models.StavkaRacuna", b =>
                {
                    b.HasOne("Knjizara.Common.Models.VrstaProizvoda", "VrstaProizvoda")
                        .WithMany()
                        .HasForeignKey("Barkod")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Knjizara.Common.Models.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("SifraRacuna")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Knjizara.Common.Models.VrstaProizvoda", b =>
                {
                    b.HasOne("Knjizara.Common.Models.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
