// <auto-generated />
using Knjizara.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Knjizara.DAL.Context.Migrations
{
    [DbContext(typeof(KnjizaraContext))]
    [Migration("20190720164639_VrsteProizvoda")]
    partial class VrsteProizvoda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knjizara.Common.Models.Proizvod", b =>
                {
                    b.Property<int>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("ProizvodID");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Knjizara.Common.Models.VrstaProizvoda", b =>
                {
                    b.Property<int>("Barkod")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena");

                    b.Property<int>("Kolicina");

                    b.Property<string>("Naziv");

                    b.Property<int>("ProizvodID");

                    b.Property<string>("Proizvodjac");

                    b.Property<string>("ZemljaPorekla");

                    b.HasKey("Barkod");

                    b.HasIndex("ProizvodID");

                    b.ToTable("VrsteProizvoda");
                });

            modelBuilder.Entity("Knjizara.Common.Models.VrstaProizvoda", b =>
                {
                    b.HasOne("Knjizara.Common.Models.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
