// <auto-generated />
using System;
using Knjizara.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Knjizara.DAL.Context.Migrations
{
    [DbContext(typeof(KnjizaraContext))]
    [Migration("20190723163200_Racun")]
    partial class Racun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knjizara.Common.Models.Proizvod", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("ProizvodId");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Knjizara.Common.Models.Racun", b =>
                {
                    b.Property<int>("SifraRacuna")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("UkupanIznos");

                    b.Property<DateTime>("VremeIzdavanja");

                    b.HasKey("SifraRacuna");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("Knjizara.Common.Models.VrstaProizvoda", b =>
                {
                    b.Property<int>("Barkod")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena");

                    b.Property<int>("Kolicina");

                    b.Property<string>("Naziv");

                    b.Property<int>("ProizvodId");

                    b.Property<string>("Proizvodjac");

                    b.Property<string>("ZemljaPorekla");

                    b.HasKey("Barkod");

                    b.HasIndex("ProizvodId");

                    b.ToTable("VrsteProizvoda");
                });

            modelBuilder.Entity("Knjizara.Common.Models.VrstaProizvoda", b =>
                {
                    b.HasOne("Knjizara.Common.Models.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
